### ISSUE TITLE
(M) (noted by DM) There is a hang when you a resource to a list, and choose to create a new list.

### ISSUE THREAD

**Issue by ptrikutam** [greencommons/commons#226] opened 2017-08-29 04:42 UTC
This may already be complete, but we need to double check once we merge in the latest code.

**Comment by ptrikutam** [comment] 2017-08-29 05:10
@davidcmiller I had trouble reproducing this. Are you able to consistently reproduce this?

**Comment by davidcmiller** [comment] 2017-09-08 20:07
I just tried several attempts and can't reproduce, since there is no longer the option to create a new list before adding the resource. I think it's fixed by subtraction.

**Closed by davidcmiller** 2017-09-08 20:07 UTC
