### ISSUE TITLE
(M) Issues w/ profile picture upload

### ISSUE THREAD

**Issue by ptrikutam** [greencommons/commons#203] opened 2017-08-29 04:02 UTC
> Can’t change profile picture? I get an application hang when I try, although once it worked. Also, not many cues for the user: I browse and choose a file and it returns to same page, same picture. Did I upload anything or not?

> Went to profile, tried to change image, but didn’t take. Clicked Green Commons home link and app hang up. Couldn’t replicate it, however.

**Comment by gtourtellot** [comment] 2017-08-30 17:41
Since it's a bug, let's move it to Up Next.

**Comment by ptrikutam** [comment] 2017-09-01 01:32
@gtourtellot done!

**Comment by ptrikutam** [comment] 2017-09-08 20:06
@nsanta if you're unable to reproduce this issue let me know.

**Comment by nsanta** [comment] 2017-09-21 16:56
@ptrikutam I can't reproduce the error locally. However, the current implementation stores the profile picture using the filesystem. This is a problem if you want to user to Heroku for production deployment (unless that we provide the correct setup [carrierwave for Heroku](https://github.com/carrierwaveuploader/carrierwave/wiki/How-to%3A-Make-Carrierwave-work-on-Heroku)).

What I suggest is let the user upload the image to S3 (through direct upload). Most of this functionality has been implemented on branch [issue-212-resource-form](https://github.com/greencommons/commons/tree/issue-212-resource-form)

**Comment by ptrikutam** [comment] 2017-09-21 17:47
@nsanta Actually, I believe it only stores photos on the filesystem locally. On production, it should use Fog to upload to S3: https://github.com/greencommons/commons/blob/master/app/uploaders/avatar_uploader.rb#L6

Or am I misunderstanding?

I'm unable to reproduce this issue on production. Can you try to reproduce the issue on production? If you can't we can just close it.

**Comment by nsanta** [comment] 2017-09-21 19:01
You are right @ptrikutam. I can't reproduce the error on production. Lets close this issue.

**Closed** 2017-09-21 19:02 UTC
Labels: bug
